name: 'Pack and publish NuGet package'

inputs:
  project:
    required: true
    description: 'Project to pack and publish.'
  pat:
    required: true
    description: 'Personal Access Token to push package.'
  
runs:
  using: 'composite'
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
        
    - name: Package
      shell: bash
      run: dotnet pack ${{ inputs.project }} --configuration Release --output publish_folder

    - name: Publish
      shell: bash
      run: dotnet nuget push publish_folder/*.nupkg --source https://nuget.pkg.github.com/mdekok --api-key ${{ inputs.pat }}
