name: 'Pack and publish NuGet package'

inputs:
  solution:
    required: true
    description: 'Solution to pack and publish.'
  pat:
    required: true
    description: 'Personal Access Token to push package.'
  
runs:
  using: 'composite'
  env:
    output_folder: ${{ github.workspace }}/output
  steps:
    - name: Package
      shell: bash
      run: dotnet pack ${{ inputs.solution }} --configuration ${{ inputs.build_config }} -o:${{ env.output_folder }}

    - name: Publish
      shell: bash
      run: dotnet nuget push ${{ env.output_folder }}/*.nupkg --source https://nuget.pkg.github.com/mdekok/index.json --api-key ${{ secrets.pat }}    
