name: 'Pack and publish NuGet package'

inputs:
  solution:
    required: true
    description: 'Solution to pack and publish.'
  pat:
    required: true
    description: 'Personal Access Token to push package.'
  
runs:
  using: 'composite'
  env:
    output_folder: ${{ github.workspace }}/output
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Package
      shell: bash
      run: dotnet pack ${{ inputs.solution }} --configuration Release --output ${{ env.output_folder }}

    - name: Publish
      shell: bash
      run: dotnet nuget push ${{ env.output_folder }}/*.nupkg --source https://nuget.pkg.github.com/mdekok/index.json --api-key ${{ secrets.pat }}
