name: Deploy Bicep file

on:
  workflow_call:
    inputs:
      action:
        description: 'Deployment action: validate, what-if or create'
        required: true
        type: string
      filepath:
        required: true
        type: string
      environment:
        required: true
        type: string
      version:
        required: true
        type: string
        default: 'latest'
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    - name: Check out
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Login Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deployment
      uses: azure/CLI@v2
      with:
        azcliversion: latest
        inlineScript: |
          az deployment group ${{ inputs.action }} \
            --template-file ${{ inputs.filepath }} \
            --resource-group ${{ vars.RESOURCE_GROUP }} \
            --parameters env=${{ vars.LABEL }} version=${{ inputs.version }} location=${{ vars.LOCATION }}
