name: Lint Bicep file

on:
  workflow_call:
    inputs:
      filepath:
        required: true
        type: string
        
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Lint
      run: az bicep build --file ${{ inputs.filepath }}
