name: Validate Bicep file

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      location:
        default: 'westeurope'
        required: true
        type: string
        
jobs:
  validate:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    - run: echo ${{ inputs.Location }}
    - name: Check out
      uses: actions/checkout@v4

    - uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Validate resources
      uses: azure/CLI@v2
      with:
        azcliversion: 2.63.0 # See: https://github.com/Azure/azure-cli/issues/29828
        inlineScript: |
          az deployment group validate \
            --template-file ./Tools/Bicep/main.bicep \
            --resource-group ${{ vars.RESOURCE_GROUP }} \
            --parameters environment="${{ vars.Label }}" location=${{ inputs.Location }}
