name: Build, test and publish NuGet package

on:
  workflow_call:
    inputs:
      solution:
        required: true
        type: string
      build_config:
        required: true
        type: string
    secrets:
      pat:
        required: true
        
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      output_folder: ${{ github.workspace }}/output

    steps:
    - name: Check out
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    - name: Restore packages
      run: dotnet restore
      
    - name: Test Test
      run: dotnet test ${{ inputs.solution }} --configuration:${{ inputs.build_config }} --no-build --verbosity normal
      
    - name: Build
      run: dotnet build ${{ inputs.solution }} --configuration:${{ inputs.build_config }} --no-restore
      
    - name: Test
      run: dotnet test ${{ inputs.solution }} --configuration:${{ inputs.build_config }} --no-build --verbosity normal

    - name: Package
      run: dotnet pack ${{ inputs.solution }} --configuration:${{ inputs.build_config }} -o:${{ env.output_folder }}

    - name: Publish
      run: dotnet nuget push ${{ env.output_folder }}/*.nupkg --source https://nuget.pkg.github.com/mdekok/index.json --api-key ${{ secrets.pat }}
    
