name: Test

on:
  workflow_dispatch:

jobs:
  warning:
    runs-on: ubuntu-latest

    steps:
    - run: echo "Starter workflow for testing initial development of workflow in branch"
    - run: exit 1 # Exit in error to indicate this workflow should by overwritten
